### ISSUE TITLE
Implementation question

### ISSUE THREAD

**Issue by Daniel030117** [xszheng2020/memorization#2]
Do you have code for calculating memorization scores? Also, in the 'compute_if_attr' within CIFAR, where is the path specified in the filename variable?

**Comment by xszheng2020** [comment]
Hi, @Daniel030117 thanks for your interest in our work.

**Do you have the code for calculating memorization scores?**
    Yes, the memorization score, which is defined as **self-influence**, is computed in [compute_if.py](https://github.com/xszheng2020/memorization/blob/master/cifar/compute_if.py)

**In the 'compute_if_attr' within CIFAR, where is the path specified in the filename variable?**
    Do you mean the pre-computed memorization attributions? You can find them in the [score_42](https://github.com/xszheng2020/memorization/tree/master/cifar/saved/score_42) folder

**Comment by xszheng2020** [comment]
And, if you are interested in estimating memorization (self-influence) scores, I suggest using a new method called **TRAK** rather than the original **Influence Functions** nowadays.

You may take a look at this repo [LLM-TRAK](https://github.com/xszheng2020/LLM-TRAK).
![截屏2024-03-08 下午1 32 32](https://github.com/xszheng2020/memorization/assets/101038474/b084c463-5a44-4a8e-bf73-f7f83e09688e)

**Comment by Daniel030117** [comment]
The filename path here is in saved/random/0/42/checkpoint, but I couldn't find the checkpoint folder.

**Comment by xszheng2020** [comment]
We did not share the model checkpoints because they are too large.

We only shared the pre-computed memorization attributions.

You can obtain the checkpoints by conducting the training by yourself.

`CUDA_VISIBLE_DEVICES=0 python -u train.py --SEED=42 --SAVE_CHECKPOINT=True > log/random/0/log_seed_42.txt`

**Comment by Daniel030117** [comment]
It shows that NO log/random/0/log_seed_42.txt.

**Comment by xszheng2020** [comment]
first `mkdir -p log/random/0` as shown in [run_random_0.sh](https://github.com/xszheng2020/memorization/blob/master/cifar/scripts/run_random_0.sh).

**Comment by Daniel030117** [comment]
It shows No such file or directory: './data/cifar_10/train/6508.npy'

**Comment by xszheng2020** [comment]
:) 

Please first follow the [README.md](https://github.com/xszheng2020/memorization/blob/master/README.md) ...

> Download the CIFAR-10, [SNLI](https://nlp.stanford.edu/projects/snli/snli_1.0.zip), [SST](https://nlp.stanford.edu/sentiment/index.html), [Yahoo! Answer](https://drive.google.com/uc?export=download&id=0Bz8a_Dbh9Qhbd2JNdDBsQUdocVU) datasets from web and then process them using the 00_EDA.ipynb

**Comment by Daniel030117** [comment]
How to run 00_EDA.ipynb

**Comment by Daniel030117** [comment]
Which part of the CIFAR project calculates the memorization score?

**Comment by Daniel030117** [comment]
thankyou
